[package]
name = "rust-cli-twitch"
version = "0.1.0"
edition = "2021"

[[bin]]
edition = "2021"
name = "rust-cli-twitch"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.188", features = [ "derive" ] }
serde_json = "1.0.107"
